FROM ubuntu:focal

# Prevent apt from prompting for user input
ENV DEBIAN_FRONTEND=noninteractive

# Combine RUN commands to reduce layers and use cache effectively
RUN apt-get update && \
    apt-get install -y \
    curl \
    git \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /home/app

# Copy package files first to leverage Docker cache
COPY package.json ./

# Copy application files
COPY main.sh script.js ./

RUN npm install
# Give execution permission to main.sh
RUN chmod +x main.sh

# Set the entrypoint to execute the main.sh script
ENTRYPOINT [ "/home/app/main.sh" ]